### ISSUE TITLE
Installation problem rake task breaks if Postgres is not setup

### ISSUE THREAD

**Issue by jordelver** [pushtype/push_type#1]
If you run the install (`rails g push_type:install`) without first changing the `config/database.yml` to use Postgres, the error below occurs.

```shell
[I] ~/D/P/p/push_type_demo (master) $ rails g push_type:install
      create  config/initializers/push_type.rb
      insert  config/routes.rb
- Copying migrations
        rake  railties:install:migrations
Copied migration 20150824205449_create_push_type_users.push_type.rb from push_type
Copied migration 20150824205450_create_push_type_nodes.push_type.rb from push_type
Copied migration 20150824205451_create_push_type_node_hierarchies.push_type.rb from push_type
Copied migration 20150824205452_create_push_type_assets.push_type.rb from push_type
Copied migration 20150824205453_create_push_type_taxonomies.push_type.rb from push_type
Copied migration 20150824205454_create_push_type_taxonomy_hierarchies.push_type.rb from push_type
Copied migration 20150824205455_add_field_store_default_values.push_type.rb from push_type
Copied migration 20150824205456_devise_extend_push_type_users.push_type_auth.rb from push_type_auth
- Running migrations
        rake  db:migrate
== 20150824205449 CreatePushTypeUsers: migrating ==============================
-- extension_enabled?("uuid-ossp")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `extension_enabled?' for #<CreatePushTypeUsers:0x007fc0e27e3970>/Users/jord/Dropbox/Projects/push_type/push_type_demo/db/migrate/20150824205449_create_push_type_users.push_type.rb:4:in `change'
NoMethodError: undefined method `extension_enabled?' for #<CreatePushTypeUsers:0x007fc0e27e3970>
/Users/jord/Dropbox/Projects/push_type/push_type_demo/db/migrate/20150824205449_create_push_type_users.push_type.rb:4:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

We should probably a) Handle this error better; and b) Explicitly mention editing the `config/database.yml` in the setup instructions. The installation instructions say "Assuming you have a Rails app ready to go", but I think this will be a common mistake.

We can find out what database is being used with this

```ruby
ActiveRecord::Base.connection.adapter_name
=> "PostgreSQL"
```

What do you think?

**Comment by aaronrussell** [comment]
https://discuss.pushtype.org/t/installation-rake-task-breaks-if-postgres-is-not-setup/20/8
