### ISSUE TITLE
Installation fails with undefined method `extension_enabled?'

### ISSUE THREAD

**Issue by brandondrew** [pushtype/push_type#16]
This basic error happens with Rails 5 on Ruby 2.3.0 and Rails 4.2.6 on Ruby 2.3.1:
```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `extension_enabled?' for #<CreatePushTypeUsers:0x007ff183e6fab0>
/Users/brandon/Code/Ruby/x.5.pushtype/db/migrate/20161101173650_create_push_type_users.push_type.rb:4:in `change'
NoMethodError: undefined method `extension_enabled?' for #<CreatePushTypeUsers:0x007ff183e6fab0>
/Users/brandon/Code/Ruby/x.5.pushtype/db/migrate/20161101173650_create_push_type_users.push_type.rb:4:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by aaronrussell** [comment]
Is your app using Postgres?

**Comment by brandondrew** [comment]
It was a brand-new app created just for PushType. Obviously I made some false assumptions.

**Comment by TheKramers** [comment]
Are you saying I need to be logged into the shell as postgres in order to run the installation?

Also, the installation requires Nodejs, which isn't listed as a dependancy and it should be.
