### ISSUE TITLE
In 0.10.0.beta.5 wrong exception when 404 should be raised

### ISSUE THREAD

**Issue by aaronrussell** [pushtype/push_type#21]
When `config.home_slug = false` then `raise_404` encounters undefined method on `home_node_path`.

```
undefined method `home_node_path' for #<ActionDispatch::Routing::RoutesProxy:0x007f9a5ab42a98>
actionpack (5.0.0.1) lib/action_dispatch/routing/routes_proxy.rb:37:in `method_missing'
push_type_core (0.10.0.beta.5) app/controllers/front_end_controller.rb:38:in `root_path?'
push_type_core (0.10.0.beta.5) app/controllers/front_end_controller.rb:42:in `raise_404'
```

**Comment by aaronrussell** [comment]
See 9384de1.
