### ISSUE TITLE
Various Install Errors with Rails 5

### ISSUE THREAD

**Issue by dfockler** [pushtype/push_type#28]
I continue to get various errors when running `rails g push_type:install`. I tried to setup a project in both Rails 5.0.1 with Ruby 2.4.0, as well as Rails 5.0.1 with Ruby 2.2.5. Both times I got different errors. With 

Ruby 2.4.0
```
/Users/daniel/.rubies/ruby-2.4.0/lib/ruby/2.4.0/fileutils.rb:120:in `chdir': No such file or directory - getcwd (Errno::ENOENT)
....
from /Users/daniel/.gem/ruby/2.4.0/gems/push_type_core-0.10.2/lib/generators/push_type/install/install_generator.rb:19:in `install_migrations'
```

Ruby 2.2.5
```
/Users/daniel/.gem/ruby/2.2.5/gems/push_type_auth-0.10.2/app/controllers/concerns/push_type/api_authentication_methods.rb:26: syntax error, unexpected '.' (SyntaxError)
      params[:token] || request.headers['Authorization']&.split&.last
```

I also tried setting up a project with Rails 4.2.0 and Ruby 2.4.0 and the same command doesn't do anything at all. Hope this helps find some way to fix it. Or it could always be my machine somehow.

**Comment by dfockler** [comment]
Ran it again using Rails 5.0.1 and Ruby 2.4.0 and it worked this time. Weird
